# Generated by Django 5.2.1 on 2025-05-22 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('year_founded', models.IntegerField()),
                ('number_of_employees', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number', models.IntegerField()),
                ('model', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('year_made', models.IntegerField()),
                ('distance_km', models.IntegerField()),
                ('type', models.CharField(choices=[('S', 'Sedan'), ('suv', 'SUV'), ('H', 'Hatchback'), ('C', 'Coupe')], max_length=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to='car_images/')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarDealership.distributor')),
            ],
        ),
    ]
