# Generated by Django 5.2.1 on 2025-05-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMidterm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
