# Generated by Django 5.2.1 on 2025-05-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMidterm', '0002_alter_property_reserved_alter_property_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
